# write a program to input eight numbers from the user and displaed all the unique numbers (once)
s = set()
n = input("enter a number:")
s.add(int(n))
n = input("enter a number:")
s.add(int(n))
n = input("enter a number:")
s.add(int(n))
n = input("enter a number:")
s.add(int(n))
n = input("enter a number:")
s.add(int(n))
n = input("enter a number:")
s.add(int(n))
n = input("enter a number:")
s.add(int(n))
n = input("enter a number:")
s.add(int(n))
print(s)